services:
  prometheus:
    image: prom/prometheus:main
    container_name: prometheus
    ports:
      - '9090:9090'
    volumes:
      - ./src/main/resources/prometheus.yaml:/etc/prometheus/prometheus.yml

  grafana:
    image: grafana/grafana:main
    container_name: grafana
    restart: always
    ports:
      - '3000:3000'

  loki:
    image: grafana/loki:main
    container_name: loki
    ports:
      - '3100:3100'
    volumes:
      - ./src/main/resources/loki-config.yaml:/etc/loki/local-config.yaml
    command: -config.file=/etc/loki/local-config.yaml

  promtail:
    image: grafana/promtail:main
    container_name: promtail
    volumes:
      - ./src/main/resources/promtail-config.yaml:/etc/promtail/config.yaml
      - /var/log:/var/log
    command: -config.file=/etc/promtail/config.yml
