spring:
  application:
    name: ${APP_NAME}
  profiles:
    active: ${PROFILE}
  config:
    import: optional:configserver:${CLOUD_CONFIG_URL}

management:
  server:
    port: ${ACTUATOR_PORT}
  endpoints:
    prometheus:
      enabled: true
    web:
      exposure:
        include: refresh, prometheus